# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Võ Minh Duy
author:
  name: Võ Minh Duy
  birthday: 6 November, 1996
  email: minhduy.ringo@gmail.com
  github: minhduy-ringo
  job-title: Software Engineer
  phonenumber: (+84) 352837767
  location: Ho Chi Minh City, Viet Nam
  description: >-
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
    Phasellus ex neque, porttitor eu rhoncus at, luctus quis sapien. 
    Donec pretium euismod lacus vitae pharetra. Aenean in leo dolor. 
description: >- # this means to ignore newlines until "baseurl:"
  A small website I make to use as a resume, using Jekyll, Bootstrap and hosted by Github Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

timezone: Asia/Bangkok
encoding: utf-8

# sass setting
sass:
  sass_dir: /assets/css
  style:    compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
